name: 'shopify'
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]

models:
  shopify:
    vars: #all should be schema.table
      checkouts_table:        #checkouts
      customers_table:        #customers
      orders_table:           #orders
      transactions_table:     #transactions
      products_table:         #products
      refunds_table:          #order_refunds
      refund_items_table:     #order_refund_items
      refund_adjustments_table: #order_refund_adjustments
      discount_codes_table:   #orders__discount_codes
      order_items_table:      #orders__line_items
      products_variants_table: #products__variants
